/* Builds the living task vegetables and keeps their movements inside the field. */
window.Farm=(()=>{
 const speciesByPriority={urgent:'tomato',medium:'pumpkin',chill:'broccoli'};let tasks=[],id=0,plot,shovel=false,completed=0,last=performance.now(),facingCount={tomato:0,pumpkin:0,broccoli:0};
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const safe=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function position(t){t.el.style.left=t.x+'vw';t.el.style.top=t.y+'vh'}
 function makeTask(name,priority,note=''){const type=speciesByPriority[priority],el=document.createElement('article'),t={id:++id,name,priority,note,type,el,x:18+Math.random()*65,y:45+Math.random()*22,vx:(Math.random()-.5)*.34,vy:(Math.random()-.5)*.22,paused:false},flipped=facingCount[type]++%2===1;el.className=`task ${priority} ${type}-asset${flipped?' flipped':''}`;el.style.setProperty('--tilt',`${Math.round(-5+Math.random()*10)}deg`);el.style.setProperty('--scale',`${(.88+Math.random()*.16).toFixed(2)}`);el.style.setProperty('--idle-delay',`${(-Math.random()*1.6).toFixed(2)}s`);el.style.setProperty('--idle-speed',`${(1.4+Math.random()*.9).toFixed(2)}s`);el.innerHTML=`<div class="sign" data-note="${safe(note||name)}">${safe(name)}</div><div class="creature asset-creature"><img class="veggie-art" src="assets/${type}.svg" alt="${type}" draggable="false" /></div>`;el.onclick=()=>shovel&&harvest(t);el.onmouseenter=()=>t.paused=true;el.onmouseleave=()=>t.paused=false;plot.append(el);tasks.push(t);position(t);return t}
 function burst(x,y){const box=document.querySelector('#sparkles');for(let i=0;i<8;i++){const e=document.createElement('i');e.className='spark';e.textContent='✦';e.style.left=x+'vw';e.style.top=y+'vh';e.style.setProperty('--x',`${(Math.random()-.5)*100}px`);e.style.setProperty('--y',`${(Math.random()-.5)*90}px`);box.append(e);setTimeout(()=>e.remove(),700)}}
 function harvest(t){if(t.el.classList.contains('leaving'))return;try{FarmAudio.dig()}catch(error){}t.el.classList.add('leaving');burst(t.x+5,t.y+7);setTimeout(()=>{t.el.remove();tasks=tasks.filter(x=>x!==t);document.querySelector('#completed-count').textContent=++completed;document.dispatchEvent(new CustomEvent('farm:update',{detail:{name:t.name,note:t.note,priority:t.priority,type:t.type}}))},560)}
 function chase(){const u=tasks.find(t=>t.priority==='urgent'&&!t.paused&&Math.random()<.55),low=tasks.find(t=>t.priority!=='urgent'&&!t.paused);if(!u||!low)return;u.chase=low;u.el.classList.add('chasing');low.el.classList.add('scared');setTimeout(()=>{u.chase=null;u.el.classList.remove('chasing');low.el.classList.remove('scared')},2400)}
 function tick(now){const dt=Math.min(2,(now-last)/16);last=now;tasks.forEach(t=>{if(t.paused)return;const s=t.priority==='urgent'?.8:t.priority==='medium'?.48:.15;if(t.chase){const dx=t.chase.x-t.x,dy=t.chase.y-t.y,d=Math.hypot(dx,dy)||1;t.vx+=dx/d*.045;t.vy+=dy/d*.04}else if(Math.random()<.012){t.vx+=(Math.random()-.5)*.18;t.vy+=(Math.random()-.5)*.13}t.vx=clamp(t.vx,-s,s);t.vy=clamp(t.vy,-s*.6,s*.6);t.x=clamp(t.x+t.vx*dt,7,82);t.y=clamp(t.y+t.vy*dt,42,67);if(t.x===7||t.x===82)t.vx*=-1;if(t.y===42||t.y===67)t.vy*=-1;position(t)});requestAnimationFrame(tick)}
 function init(){plot=document.querySelector('#plot');requestAnimationFrame(tick);setInterval(chase,7200)}return{init,makeTask,burst,get tasks(){return tasks},setHarvestCount(value){completed=Math.max(0,Number(value)||0);document.querySelector('#completed-count').textContent=completed},toggleShovel(){return shovel=!shovel}};
})();
