/* The scarecrow has a small, self-contained dialogue system and only talks through the server. */
document.addEventListener('DOMContentLoaded',()=>{
  const wrap=document.querySelector('#scarecrow-wrap'),dialogue=document.querySelector('#scarecrow-dialogue'),message=document.querySelector('#scarecrow-message'),form=document.querySelector('#scarecrow-form'),input=document.querySelector('#scarecrow-input'),spark=document.querySelector('#scarecrow-spark');
  const idleLines=['Those peppers have been arguing all morning.','The pumpkins look a little anxious today.','The broccoli seems happy.','I think today’s harvest will be a good one.','The field feels calmer than yesterday.'];
  function open(){dialogue.classList.remove('hidden');wrap.setAttribute('aria-expanded','true');input.focus()}function shut(){dialogue.classList.add('hidden');wrap.setAttribute('aria-expanded','false')}function speak(line){message.textContent=line;open()}
  function farmState(){const groups={urgent:[],medium:[],chill:[]};(Farm.tasks||[]).forEach(item=>groups[item.priority]?.push(item.type.replaceAll('-',' ')));return {...groups,harvestCount:Number(document.querySelector('#completed-count').textContent)||0}}
  function idle(){if(dialogue.classList.contains('hidden'))speak(idleLines[Math.floor(Math.random()*idleLines.length)]);window.setTimeout(idle,40000+Math.random()*50000)}window.setTimeout(idle,40000+Math.random()*50000);
  wrap.addEventListener('mouseenter',()=>{try{FarmAudio.hover()}catch(error){}});wrap.addEventListener('click',open);wrap.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}});document.addEventListener('click',event=>{if(!dialogue.classList.contains('hidden')&&!dialogue.contains(event.target)&&!wrap.contains(event.target))shut()});document.addEventListener('keydown',event=>event.key==='Escape'&&shut());
  form.addEventListener('submit',async event=>{event.preventDefault();const question=input.value.trim();if(!question)return;input.value='';wrap.classList.add('pondering');message.textContent=['Hmm...','Let me watch the field...','The vegetables are telling me something...','I’ve watched this farm through many seasons...'][Math.floor(Math.random()*4)];try{const response=await fetch('/api/scarecrow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:question,farm:farmState()})});const data=await response.json();if(!response.ok)throw new Error(data.error);message.textContent=data.reply;wrap.classList.remove('pondering');wrap.classList.add('reply');spark.style.animation='none';void spark.offsetWidth;spark.style.animation='scarecrow-spark .7s ease-out';setTimeout(()=>wrap.classList.remove('reply'),800)}catch(error){message.textContent="Hmm... the wind carried my thoughts away. Let's try again.";wrap.classList.remove('pondering')}});
});
